[package]
name = "server-grpc"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
futures = "0.3"
log = "0.4"
async-trait = "0.1"
cached = "0.23"
parking_lot = "0.11" # move to base

server-base = { path = "../server-base" }
server-state = { path = "../server-state" }